bracketSpacing: true
endOfLine: auto
printWidth: 100
singleQuote: false
tabWidth: 2
trailingComma: "es5"

importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
importOrderParserPlugins: ["typescript"]
importOrderSeparation: true
importOrderSortSpecifiers: true

overrides:
  - files: "*.sol"
    options:
      compiler: "0.8.15"
      tabWidth: 4
      useTabs: false
      bracketSpacing: true
      explicitTypes: "always"
